name: CI/CD - Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build, Test, Dockerize and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Rodar testes
        run: mvn test

      - name: Build Docker image
        run: docker build -t ayanokoujifl/catalogo-de-carros:latest .

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push da imagem para o Docker Hub
        run: docker push ayanokoujifl/catalogo-de-carros:latest

      - name: Instalar Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy automático no Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT : ${{secrets.RAILWAY_PROJECT}}
        run: |
          railway up -- --project $RAILWAY_PROJECT --service catalogo-de-carros
