name: CI/CD - Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Rodar testes
        run: mvn test
  push:
    name: Push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: docker build -t ayanokoujifl/catalogo-de-carros:latest .

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push da imagem para o Docker Hub
        run: docker push ayanokoujifl/catalogo-de-carros:latest
  deploy:
    name: Deploy no Railway
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT : ${{secrets.RAILWAY_PROJECT}}
    steps:
       - uses: actions/checkout@v3
       - run: railway up --service=${{ env.RAILWAY_PROJECT }}
